import './globals.css'
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: 'FlixChill',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader color='rgb(220 38 38)' height={4} easing="ease"/>
        {children}
        </body>
    </html>
  )
}
